### ISSUE TITLE
HTTP 500 on Item Creation: is_favorite error

### ISSUE THREAD

**Issue by eozd** [bounswe/bounswe2017group10#319]
#### Issue description
- I am not able to create a culture item on my local backend with commit id 7f282e3e2a25bf72b8601b77edb09acd08324ca7 due to internal server error.

#### Steps to reproduce the issue
1. Run the version of the server with the above given commit id version
2. Send a create item request with any valid body

#### What's the expected result?
- Creating a culture item successfully

#### What's the actual result?
- Internal server error

### Platform Details
- Linux asus_arch 4.13.12-1-ARCH #1 SMP PREEMPT Wed Nov 8 11:54:06 CET 2017 x86_64 GNU/Linux

#### Django Log
```python
Internal Server Error: /cultural_heritage_item
Traceback (most recent call last):
  File "/home/eozd/projects/atlas_backend/Atlas/backend/atlasenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
psycopg2.IntegrityError: null value in column "is_favorite" violates not-null constraint
DETAIL:  Failing row contains (30, title, , , , , t, 2017-12-01, 2017-12-01, 2, null, null, 37.913600, 29.118700, 1982, 1980, Pamukkale).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/eozd/projects/atlas_backend/Atlas/backend/atlasenv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/eozd/projects/atlas_backend/Atlas/backend/atlasenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/eozd/projects/atlas_backend/Atlas/backend/atlasenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/eozd/projects/atlas_backend/Atlas/backend/atlasenv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/eozd/projects/atlas_backend/Atlas/backend/atlasenv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/eozd/projects/atlas_backend/Atlas/backend/atlasenv/lib/python3.6/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/home/eozd/projects/atlas_backend/Atlas/backend/atlasenv/lib/python3.6/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/eozd/projects/atlas_backend/Atlas/backend/atlasenv/lib/python3.6/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/eozd/projects/atlas_backend/Atlas/backend/atlasenv/lib/python3.6/site-packages/rest_framework/generics.py", line 244, in post
    return self.create(request, *args, **kwargs)
  File "/home/eozd/projects/atlas_backend/Atlas/backend/atlas/views.py", line 44, in create
    self.perform_create(serializer)
  File "/home/eozd/projects/atlas_backend/Atlas/backend/atlas/views.py", line 30, in perform_create
    serializer.save()
  File "/home/eozd/projects/atlas_backend/Atlas/backend/atlasenv/lib/python3.6/site-packages/rest_framework/serializers.py", line 214, in save
    self.instance = self.create(validated_data)
  File "/home/eozd/projects/atlas_backend/Atlas/backend/atlas/serializers.py", line 38, in create
    heritage_item = Cultural_Heritage.objects.create(**validated_data)
  File "/home/eozd/projects/atlas_backend/Atlas/backend/atlasenv/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/eozd/projects/atlas_backend/Atlas/backend/atlasenv/lib/python3.6/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/eozd/projects/atlas_backend/Atlas/backend/atlasenv/lib/python3.6/site-packages/django/db/models/base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/eozd/projects/atlas_backend/Atlas/backend/atlasenv/lib/python3.6/site-packages/django/db/models/base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/eozd/projects/atlas_backend/Atlas/backend/atlasenv/lib/python3.6/site-packages/django/db/models/base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/eozd/projects/atlas_backend/Atlas/backend/atlasenv/lib/python3.6/site-packages/django/db/models/base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "/home/eozd/projects/atlas_backend/Atlas/backend/atlasenv/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/eozd/projects/atlas_backend/Atlas/backend/atlasenv/lib/python3.6/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/eozd/projects/atlas_backend/Atlas/backend/atlasenv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1107, in execute_sql
    cursor.execute(sql, params)
  File "/home/eozd/projects/atlas_backend/Atlas/backend/atlasenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/eozd/projects/atlas_backend/Atlas/backend/atlasenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/home/eozd/projects/atlas_backend/Atlas/backend/atlasenv/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/eozd/projects/atlas_backend/Atlas/backend/atlasenv/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/eozd/projects/atlas_backend/Atlas/backend/atlasenv/lib/python3.6/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "is_favorite" violates not-null constraint
DETAIL:  Failing row contains (30, title, , , , , t, 2017-12-01, 2017-12-01, 2, null, null, 37.913600, 29.118700, 1982, 1980, Pamukkale).

[01/Dec/2017 19:52:09] [35;1m"POST /cultural_heritage_item HTTP/1.1" 500 22539[0m

```

**Comment by eozd** [comment]
Apparently this issue was related with having database conflicts between branches. To fix it, you need to reset the local database:

```bash
sudo -u postgres -i
psql
drop database atlas;
create database atlas;
\q
exit

cd Atlas/backend
rm atlas/migrations/00*
python3 manage.py makemigrations atlas
python3 manage.py migrate
```
